app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^question/(?P<question_id>\d+)/$', views.question, name='question'),
    url(r'^question/(?P<question_id>\d+)/up$', views.question_vote_up, name='question_vote_up'),
    url(r'^question/(?P<question_id>\d+)/down$', views.question_vote_down, name='question_vote_down'),
    url(r'^answer/(?P<answer_id>\d+)/up$', views.answer_vote_up, name='answer_vote_up'),
    url(r'^answer/(?P<answer_id>\d+)/down$', views.answer_vote_down, name='answer_vote_down'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

vstm/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('app.urls', namespace='app')),
    url(r'users/', include('users.urls', namespace='users'))
]

app/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    votes = models.IntegerField(default=0)
    owner = models.ForeignKey(User)

    def __str__(self):
        return self.text

    def vote_up(self):
        self.votes += 1

    def vote_down(self):
        self.votes -= 1


class Answer(models.Model):
    question = models.ForeignKey(Question)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    rating = models.IntegerField(default=0)
    owner = models.ForeignKey(User)

    def rating_up(self):
        self.rating += 1

    def rating_down(self):
        self.rating -= 1

    def __str__(self):
        if len(self.text) > 50:
            return self.text[:50] + "..."
        else:
            return self.text


class Vote(models.Model):
    question = models.ForeignKey(Question)
    vote = models.IntegerField()
    owner = models.ForeignKey(User)


class AVote(models.Model):
    answer = models.ForeignKey(Answer)
    vote = models.IntegerField()
    owner = models.ForeignKey(User)

users/models.py
from django.db import models

# Create your models here.

app/forms.py
from django import forms
from .models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80, 'rows': 2})}


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80, 'rows': 2})}

app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from .models import Question, Answer, Vote, AVote
from .forms import QuestionForm, AnswerForm
from .functions import add_vote, add_answer_vote


def index(request):
    if request.method == 'POST' and request.user.is_authenticated():
        form = QuestionForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.owner = request.user
            new_entry.save()
            return HttpResponseRedirect(reverse('app:index'))
    else:
        form = QuestionForm()

    questions = Question.objects.order_by('date_added')
    context = {'questions': questions, 'form': form}
    return render(request, 'app/index.html', context)


def question(request, question_id):
    question_obj = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST' and request.user.is_authenticated():
        form = AnswerForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.owner = request.user
            new_entry.question = question_obj
            new_entry.save()
            return HttpResponseRedirect(reverse('app:question', args=[question_id]))
    else:
        form = AnswerForm()

    answers = question_obj.answer_set.order_by('date_added')
    context = {'question': question_obj, 'answers': answers, 'form':form}
    return render(request, 'app/question.html', context)


@login_required
def question_vote_up(request, question_id):
    question_obj = get_object_or_404(Question, pk=question_id)
    question_obj.vote_up()
    question_obj.save()
    add_vote(request, question_obj, 1)
    return HttpResponseRedirect(reverse('app:index'))


@login_required
def question_vote_down(request, question_id):
    question_obj = get_object_or_404(Question, pk=question_id)
    question_obj.vote_down()
    question_obj.save()
    add_vote(request, question_obj, -1)
    return HttpResponseRedirect(reverse('app:index'))


@login_required
def answer_vote_up(request, answer_id):
    answer_obj = get_object_or_404(Answer, pk=answer_id)
    answer_obj.rating_up()
    answer_obj.save()
    add_answer_vote(request, answer_obj, 1)
    return HttpResponseRedirect(reverse('app:question', args=[answer_obj.question.id]))


@login_required
def answer_vote_down(request, answer_id):
    answer_obj = get_object_or_404(Answer, pk=answer_id)
    answer_obj.rating_down()
    answer_obj.save()
    add_answer_vote(request, answer_obj, -1)
    return HttpResponseRedirect(reverse('app:question', args=[answer_obj.question.id]))

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    """Завершает сеанс работы с приложением."""
    logout(request)
    return HttpResponseRedirect(reverse('app:index'))


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('app:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

app/templates/app/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Learning Log</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                </button>
                <a class="navbar-brand" href="{% url 'app:index' %}">App</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a>Привет, {{ user.username }}.</a></li>
                        <li><a href="{% url 'users:logout' %}">log out</a></li>
                    {% else %}
                        <li><a href="{% url 'users:register' %}">register</a></li>
                        <li><a href="{% url 'users:login' %}">log in</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </div>
</body>
</html>

app/templates/app/index.html
{% extends "app/base.html" %}

{% block header %}
    {% if user.is_authenticated %}
    <form action="{% url 'app:index'%}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">add question</button>
    </form>
    {% else %}
<p>Чтобы задать вопрос <a href="{% url 'users:register' %}">зарегистрируйтесь</a> или <a href="{% url 'users:login' %}">авторизуйтесь!</a></p>
    {% endif %}
{% endblock header %}

{% block content %}
    <ul class="list-group">
    {% for question in questions %}
        <li class = "list-group-item">
            <a href="{% url 'app:question' question.id %}" class="list-group-item">
                    {{ question }}
            </a>
            Vote:
            {% if user.is_authenticated %}
            <a href="{% url 'app:question_vote_up' question.id %}" class="glyphicon glyphicon-thumbs-up"></a>
            {% endif %}
            <span id="cnt">{{ question.votes }}</span>
            {% if user.is_authenticated %}
            <a href="{% url 'app:question_vote_down' question.id %}" class="glyphicon glyphicon-thumbs-down"></a>
            {% endif %}
            <span class = "badge">{{ question.owner }}</span>
        </li>
    {% empty %}
        <li>No questions.</li>
    {% endfor %}
    </ul>
{% endblock content %}

app/templates/app/question.html
{% extends 'app/base.html' %}

{% block header %}
{% if user.is_authenticated %}
    <form action="{% url 'app:question' question.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">add answer</button>
    </form>
    {% else %}
        <p>Чтобы задать вопрос <a href="{% url 'users:register' %}">зарегистрируйтесь</a> или <a href="{% url 'users:login' %}">авторизуйтесь!</a></p>
    {% endif %}
{% endblock header %}

{% block content %}
<p>Question: {{ question }}</p>
<p>Answers: </p>
<ul>
    {% for answer in answers %}
        <li>
            <p>{{ answer.date_added|date:'M d, Y H:i' }}</p>
            <p>{{ answer.text|linebreaks }}</p>
            <p>
                Vote:
                {% if user.is_authenticated %}
                    <a href="{% url 'app:answer_vote_up' answer.id %}" class="glyphicon glyphicon-thumbs-up"></a>
                {% endif %}
                <span id="cnt">{{ answer.rating }}</span>
                {% if user.is_authenticated %}
                    <a href="{% url 'app:answer_vote_down' answer.id %}" class="glyphicon glyphicon-thumbs-down"></a>
                {% endif %}
                <span class = "badge">{{ question.owner }}</span>
            </p>
        </li>
    {% empty %}
        <li>No answers yet.</li>
    {% endfor %}
</ul>
{% endblock content %}

users/templates/users/login.html
{% extends 'app/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}
    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Log in</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'app:index' %}" />
    </form>

{% endblock content %}

users/templates/users/register.html
{% extends 'app/base.html' %}
{% load bootstrap3 %}

{% block content %}
    <form method="post" action="{% url 'users:register' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Log in</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'app:index' %}" />
    </form>

{% endblock content %}